const axios = require('axios');

const GROQ_API_KEY = process.env.GROQ_API_KEY;

const generatePreVisitSummary = async (symptoms) => {
  if (!GROQ_API_KEY || GROQ_API_KEY === 'your_groq_api_key' || GROQ_API_KEY === 'your_openai_api_key') {
    throw new Error('Groq API key missing or invalid');
  }

  const prompt = `Analyse these symptoms and return: urgency level (Low / Medium / High), chief complaint, and three suggested questions for the doctor. Symptoms: ${symptoms}
  
Provide the output strictly in JSON format with the following keys:
- "urgency_level" (must be exactly "Low", "Medium", or "High")
- "chief_complaint" (string)
- "suggested_questions" (array of exactly 3 strings)`;

  try {
    const response = await axios.post(
      'https://api.groq.com/openai/v1/chat/completions',
      {
        model: 'qwen/qwen3.6-27b', // fast, handles JSON well
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.2,
        response_format: { type: "json_object" }
      },
      {
        headers: {
          'Authorization': `Bearer ${GROQ_API_KEY}`,
          'Content-Type': 'application/json'
        },
        timeout: 10000 // 10 second timeout
      }
    );

    const content = response.data.choices[0].message.content;
    const parsed = JSON.parse(content);

    // Validate the output
    if (!['Low', 'Medium', 'High'].includes(parsed.urgency_level)) {
      throw new Error('Invalid urgency level returned from AI');
    }
    if (!parsed.chief_complaint || typeof parsed.chief_complaint !== 'string') {
      throw new Error('Invalid chief complaint returned from AI');
    }
    if (!Array.isArray(parsed.suggested_questions) || parsed.suggested_questions.length !== 3) {
      throw new Error('Invalid suggested questions returned from AI');
    }

    return parsed;
  } catch (error) {
    console.error('LLM Pre-Visit Summary Error:', error.message);
    throw error; // Let the caller handle the graceful fallback
  }
};

const generatePostVisitSummary = async (notes, prescription) => {
  if (!GROQ_API_KEY || GROQ_API_KEY === 'your_groq_api_key' || GROQ_API_KEY === 'your_openai_api_key') {
    throw new Error('Groq API key missing or invalid');
  }

  const prompt = `You are writing a short patient-facing summary of a completed doctor visit.

Use only the information provided below.

Write 2-3 natural sentences. Mention the main reason for the visit, the doctor's advice, and the prescribed medication if one was provided.

Do not add medical advice, diagnoses, medications, follow-up instructions, or information that is not present in the provided notes.

Output only the final patient-facing summary. Do not provide analysis or reasoning.

Clinical notes:
${notes}

Prescription:
${prescription || "No prescription provided."}`;

  try {
    const response = await axios.post(
      'https://api.groq.com/openai/v1/chat/completions',
      {
        model: 'qwen/qwen3.6-27b',
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.5,
        reasoning_effort: "none",
        reasoning_format: "hidden"
      },
      {
        headers: {
          'Authorization': `Bearer ${GROQ_API_KEY}`,
          'Content-Type': 'application/json'
        },
        timeout: 10000
      }
    );

    let result = response.data.choices[0].message.content.trim();
    
    // Remove <think>...</think> blocks generated by reasoning models
    result = result.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();
    
    // Clean up generic meta-text preambles
    result = result.replace(/^(Here is|Here's).*?:/gim, '').trim();
    result = result.replace(/^(Final answer|Summary|Visit Summary|Patient Summary):/gim, '').trim();
    result = result.replace(/^Sure,? here.*?:/gim, '').trim();

    return result;
  } catch (error) {
    console.error('LLM Post-Visit Summary Error:', error.message);
    throw error;
  }
};

module.exports = { generatePreVisitSummary, generatePostVisitSummary };
